### ISSUE TITLE
using mamba solver for conda

### ISSUE THREAD

**Issue by LinearParadox** [theislab/zellkonverter#107]
The mamba solver is much faster than the default conda solver and would likely speed up the building environment step. Is it possible to support at least a toggle for this?

**Comment by lazappi** [comment]
Setting up the environment is handled by **{basilisk}**, so that would need to be handled there https://github.com/LTLA/basilisk.

I think the latest version of **conda** now uses **mamba** by default so it might be enough to update that within **{basilisk}**.

**Comment by LTLA** [comment]
Happy to take a PR to update the default miniconda version. Though I tried to do that last time and the BioC build machines kept timing out, so that would have to be resolved.

**Comment by vjcitn** [comment]
Just seeing this now.  I'd like to help move this forward.  Using the 3.18 bioconductor_docker container, I see that the miniconda version used by basilisk is
```
https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh
```
What is a preferred Miniconda version for use in 3.19?  We will try to establish a PR and prepare the build system so that a timeout does not occur.

**Comment by LTLA** [comment]
I think we'd basically want to go to whatever the latest is - based on https://repo.anaconda.com/miniconda/, it seems to be `py311_23.11.0-2`. Probably need to discuss this on Slack to notify all maintainers, because there's a non-zero chance that everything breaks, and people would probably want a heads-up.

**Comment by lazappi** [comment]
Was this addressed somewhere? I would like to close this as I don't think it's a **{zellkonverter}** issue but just wanted to check in case this conversation is needed.

**Comment by LTLA** [comment]
Should be handled by the latest **basilisk** (see Bioconductor/basilisk#42).
