### ISSUE TITLE
Locking of H5AD files

### ISSUE THREAD

**Issue by lazappi** [theislab/zellkonverter#13]
That **AnnData** datasets are opened with `r+` by **h5py** is a real PITA. It both breaks R and is broken by R; in this case, if anyone opens a file handle (even if it's just read-only), **h5py** is not able to lock the file for writing. Conversely, R cannot open a read-only file handle if it's still locked up by **h5py**. Having an option to open files in r mode would solve this.

Originally raised in #11

**Comment by lazappi** [comment]
@LTLA Is this something that needs to be fixed in **h5py**/**anndata** or something we can change? If it's **anndata** I can talk to the authors but **h5py** might be more difficult.

**Comment by LTLA** [comment]
I don't remember the exact details, but I do remember it was a pain. It's the motivation behind the sleeping in:

https://github.com/theislab/zellkonverter/blob/6cf7947a1488bfb6298829e19690bc0c7d1b59a9/R/read.R#L63-L69

IIRC, the issue is that **h5py** locks the HDF5 file when opening it in a writeable mode. This lock seems to persist for a short period of time after the Python process terminates, thus requiring us to wait a bit before trying to open the same file in R. It also mandates the use of a separate process whenever `use_hdf5=TRUE`, as otherwise the Python process will be started by **reticulate** in the current R session and will never die (so the **h5py**-owned file handles may never close).

HDF5 uses a multi-reader-single-writer philosophy, so the lock may be a natural consequence of Python opening it in write mode. If Python instead opens it in read-only mode (`mode="r"`, I guess?), all might be well... maybe.
