### ISSUE TITLE
Mapping between SingleCellExperiment and AnnData

### ISSUE THREAD

**Issue by lazappi** [theislab/zellkonverter#8]
The current conversion functions are fairly basic and only covert expression matrices and embeddings. While this is sufficient for most analyses it would be nice to have a more complete conversion. To do that we need to come up with a consensus mapping between the two objects.

**Comment by lazappi** [comment]
Here is a summary of the current mapping:

![image](https://user-images.githubusercontent.com/6869320/84898251-3b59f680-b0a7-11ea-8c6f-b21fdd45ccd7.png)

Comments/suggestions welcome here or on the spreadsheet https://docs.google.com/spreadsheets/d/1jpPBoT7FvL4V1rV17bQ8iq4MflC2VGYwBlWwsQe_YrY/edit?usp=sharing

**Comment by LTLA** [comment]
`varm` can just be shovelled into the `rowData()` as a nested matrix. That's actually how the `reducedDims` are implemented w.r.t. `int_colData()`, I only added a getter/setter to give it some scientific meaning.

`obsp` and `varp` will require some fairly straightforward extensions to **SingleCellExperiment**. I hadn't put them in because they were not of use to me, but I guess improving conversion fidelity is as good a reason as any.

**Comment by LTLA** [comment]
It is done in 1.11.5, `colPair` and `rowPair` for `obsp` and `varp`, respectively.

**Comment by lazappi** [comment]
Nice! If I get a chance this week I will try and work on implementing conversion for the other parts.

**Comment by lazappi** [comment]
Added conversion for most things. Probably needs some more thorough testing.

**Comment by lazappi** [comment]
I think this is pretty settled now so closing this.
